markdown: rdiscount
permalink: /:year/:month/:title/
url: http://lazybios.github.com
author: lazybios
highlighter: pygments

name: LAZYBIOS
description: my blog
url: http://lazybios.com

IMG_PATH: http://freshstu.qiniudn.com
