# Site settings
title: lazybios
nickname: lazybios
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
author: lazybios
twitter_username: lazybios
github_username: lazybios

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

IMG_PATH: http://freshstu.qiniudn.com

baseurl: ""
url: "http://lazybios.com"
permalink: /:year/:month/:title/
