markdown: rdiscount
permalink: /:year/:month/:title/
url: http://lazybios.github.com
author: lazybios
highlighter: pygments

name: Freshstu
description: my blog
url: http://freshstu.com

IMG_PATH: http://freshstu.qiniudn.com
